x = input('Digíte algo: ')
print('O tipo primitivo desse valor é',type(x))
print('Só tem espaços?', x.isspace())
print('É um número?', x.isnumeric())
print('É alfabético?', x.isalpha())
print('É alfanúmerico?', x.isalnum())
print('Esta em letras maiusculas?', x.isupper())
print('Esta em minusculas?', x.islower())
print('Esta capitalizada?', x.istitle())
